# Generated by Django 3.1.7 on 2021-02-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('body', models.CharField(max_length=800)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
