# Generated by Django 3.1.7 on 2021-02-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
