# Generated by Django 3.1.7 on 2021-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210226_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='phone',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
