# Generated by Django 3.1.7 on 2021-02-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
