# Generated by Django 3.1.7 on 2021-03-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
