# Generated by Django 3.1.7 on 2021-03-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210319_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default='def.png', upload_to=''),
        ),
    ]
