# Generated by Django 3.1.7 on 2021-03-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210319_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='displayphoto',
            field=models.ImageField(blank=True, default='def.png', upload_to=''),
        ),
    ]
