# Generated by Django 3.1.7 on 2021-03-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210319_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
